// +build js, wasm

package framework

import (
	"log"

	"github.com/pkg/errors"

	"github.com/josephbudd/crud/rendererprocess/framework/lpc"
	"github.com/josephbudd/crud/rendererprocess/framework/viewtools"
	"github.com/josephbudd/crud/rendererprocess/paneling"
	addpanel "github.com/josephbudd/crud/rendererprocess/panels/AddButton/AddPanel"
	editformpanel "github.com/josephbudd/crud/rendererprocess/panels/EditButton/EditFormPanel"
	editnotreadypanel "github.com/josephbudd/crud/rendererprocess/panels/EditButton/EditNotReadyPanel"
	editselectpanel "github.com/josephbudd/crud/rendererprocess/panels/EditButton/EditSelectPanel"
	printnotreadypanel "github.com/josephbudd/crud/rendererprocess/panels/PrintButton/PrintNotReadyPanel"
	printprintpanel "github.com/josephbudd/crud/rendererprocess/panels/PrintButton/PrintPrintPanel"
	printselectpanel "github.com/josephbudd/crud/rendererprocess/panels/PrintButton/PrintSelectPanel"
	removeformpanel "github.com/josephbudd/crud/rendererprocess/panels/RemoveButton/RemoveFormPanel"
	removenotreadypanel "github.com/josephbudd/crud/rendererprocess/panels/RemoveButton/RemoveNotReadyPanel"
	removeselectpanel "github.com/josephbudd/crud/rendererprocess/panels/RemoveButton/RemoveSelectPanel"
)

/*

	DO NOT EDIT THIS FILE.

	This file is generated by kickasm and regenerated by rekickasm.

*/

// DoPanels builds and runs the panels.
func DoPanels(quitChan, eojChan chan struct{}, receiveChan lpc.Receiving, sendChan lpc.Sending,
	help *paneling.Help) (err error) {
	
	defer func() {
		if err != nil {
			err = errors.WithMessage(err, "DoPanels")
			log.Println("Error: " + err.Error())
		}
	}()

	// 1. Prepare the spawn panels.

	// 2. Construct the panel code.
	var addPanel *addpanel.Panel
	if addPanel, err = addpanel.NewPanel(quitChan, eojChan, receiveChan, sendChan, help); err != nil {
		return
	}
	var editFormPanel *editformpanel.Panel
	if editFormPanel, err = editformpanel.NewPanel(quitChan, eojChan, receiveChan, sendChan, help); err != nil {
		return
	}
	var editNotReadyPanel *editnotreadypanel.Panel
	if editNotReadyPanel, err = editnotreadypanel.NewPanel(quitChan, eojChan, receiveChan, sendChan, help); err != nil {
		return
	}
	var editSelectPanel *editselectpanel.Panel
	if editSelectPanel, err = editselectpanel.NewPanel(quitChan, eojChan, receiveChan, sendChan, help); err != nil {
		return
	}
	var printNotReadyPanel *printnotreadypanel.Panel
	if printNotReadyPanel, err = printnotreadypanel.NewPanel(quitChan, eojChan, receiveChan, sendChan, help); err != nil {
		return
	}
	var printPrintPanel *printprintpanel.Panel
	if printPrintPanel, err = printprintpanel.NewPanel(quitChan, eojChan, receiveChan, sendChan, help); err != nil {
		return
	}
	var printSelectPanel *printselectpanel.Panel
	if printSelectPanel, err = printselectpanel.NewPanel(quitChan, eojChan, receiveChan, sendChan, help); err != nil {
		return
	}
	var removeFormPanel *removeformpanel.Panel
	if removeFormPanel, err = removeformpanel.NewPanel(quitChan, eojChan, receiveChan, sendChan, help); err != nil {
		return
	}
	var removeNotReadyPanel *removenotreadypanel.Panel
	if removeNotReadyPanel, err = removenotreadypanel.NewPanel(quitChan, eojChan, receiveChan, sendChan, help); err != nil {
		return
	}
	var removeSelectPanel *removeselectpanel.Panel
	if removeSelectPanel, err = removeselectpanel.NewPanel(quitChan, eojChan, receiveChan, sendChan, help); err != nil {
		return
	}

	// 3. Size the app.
	viewtools.SizeApp()

	// 4. Start each panel's message and event dispatchers.
	addPanel.StartDispatchers()
	editFormPanel.StartDispatchers()
	editNotReadyPanel.StartDispatchers()
	editSelectPanel.StartDispatchers()
	printNotReadyPanel.StartDispatchers()
	printPrintPanel.StartDispatchers()
	printSelectPanel.StartDispatchers()
	removeFormPanel.StartDispatchers()
	removeNotReadyPanel.StartDispatchers()
	removeSelectPanel.StartDispatchers()

	// 5. Start each panel's initial calls.
	addPanel.InitialJobs()
	editFormPanel.InitialJobs()
	editNotReadyPanel.InitialJobs()
	editSelectPanel.InitialJobs()
	printNotReadyPanel.InitialJobs()
	printPrintPanel.InitialJobs()
	printSelectPanel.InitialJobs()
	removeFormPanel.InitialJobs()
	removeNotReadyPanel.InitialJobs()
	removeSelectPanel.InitialJobs()

	return
}
