package store

import (
	"strings"
	
	"github.com/pkg/errors"
	"github.com/josephbudd/crud/domain/store/storer"
)

/*
	DO NOT EDIT THIS FILE.

	USE THE TOOL kickstore TO ADD OR REMOVE STORES.

	kickstore WILL EDIT THIS FILE FOR YOU.
*/

/*
	Package main's func buildStores() will build a pointer to a type Stores.
	It will eventually end up being passed to your lpc message handlers
	  so that they can use the stores.
*/

// Stores is each of the application's storers.
// Each storer is defined here as an interface.
type Stores struct {
	Contact storer.ContactStorer
}

// Close closes every store.
// It returns all of the errors as one single error.
func (stores *Stores) Close() (err error) {

	errList := make([]string, 0, 1)
	defer func() {
		if len(errList) > 0 {
			msg := strings.Join(errList, "\n")
			err = errors.New(msg)
		}
	}()

	if err = stores.Contact.Close(); err != nil {
		errList = append(errList, err.Error())
	}
	return
}
